Update metering in KKP 2.21
kubermatic/docs pull request #1239
Opened 2022-11-04 12:05 UTC by WeirdMachine

Backports metering docs to KKP 2.21 

Add new added Average Cluster Machines value to docs

2022-11-04 12:05 UTC, WeirdMachine commented
/hold

Wait for KKP 2.21 patch release

2022-11-11 11:24 UTC, embik requested changes
I think there was a copy-paste issue, other than that it looks good.

2022-11-14 11:59 UTC, WeirdMachine commented on content/kubermatic/v2.21/tutorials-howtos/metering/_index.en.md
> +![Navigation to Metering configuration and reports](/img/kubermatic/main/tutorials/metering_admin_panel_location.png?classes=shadow,border "Navigation to Metering configuration and reports")
Ai copy paste error, thanks for catching this.

2022-11-14 12:01 UTC, WeirdMachine commented
/unhold

2022-11-14 12:03 UTC, embik approved these changes

2022-11-14 12:04 UTC, merged