Add KubeVirt migration steps
kubermatic/docs pull request #1363
Opened 2023-02-14 15:51 UTC by mfranczy

Signed-off-by: Marcin Franczyk <marcin0franczyk@gmail.com>

2023-02-15 15:09 UTC, mfranczy commented
@embik so as we agreed, I would like to keep the migration in the cloud provider section and link it to the upgrade procedure.

2023-02-15 15:11 UTC, mfranczy commented
/retest

2023-02-15 15:13 UTC, mfranczy commented
/retest

2023-02-15 15:47 UTC, embik requested changes
I know this is a super nitpick, but maybe we can adjust the headers. Everything else looks fine to me.

2023-02-15 15:47 UTC, embik commented on content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
> +### Required migration steps
Nit:

```suggestion
### Required Migration Steps
```

2023-02-15 15:47 UTC, embik commented on content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
> +#### Upgrade of KubeVirt Infrastructure cluster
```suggestion
#### Upgrade of KubeVirt Infrastructure Cluster
```

2023-02-15 15:47 UTC, embik commented on content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
> +#### Update LoadBalancer selectors
```suggestion
#### Update LoadBalancer Selectors
```

2023-02-15 15:47 UTC, embik commented on content/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt.en.md
> +Take a look into [the example](https://github.com/kubermatic/machine-controller/blob/v1.55.0/examples/kubevirt-machinedeployment.yaml) to see what has been changed.
Can we link to machine-controller v1.56.0 here, since that is the release ending up in KKP 2.22?

2023-02-16 09:26 UTC, embik approved these changes
/approve

2023-02-16 09:26 UTC, mfranczy commented
@embik I adjusted the doc to your comment. Good for another review round.

2023-02-16 09:27 UTC, embik commented
> @embik I adjusted the doc to your comment. Good for another review round.

Already lgtm'd, thanks for updating it :)

2023-02-16 09:29 UTC, merged