Add docs to import KubeOne cluster
kubermatic/docs pull request #1377
Opened 2023-02-21 17:19 UTC by Waseem826

2023-02-22 13:14 UTC, rastislavs requested changes

2023-02-22 13:14 UTC, rastislavs commented on content/kubermatic/main/tutorials-howtos/kubeone-clusters/_index.en.md
> +> KKP supports latest KubeOne code hence supported kubernetes version '>= 1.24'.
```suggestion
KKP supports latest KubeOne code hence supported Kubernetes version has to be '>= 1.24'.
```

2023-02-22 13:14 UTC, rastislavs commented on content/kubermatic/main/tutorials-howtos/kubeone-clusters/_index.en.md
> +We need to use an older KubeOne version to upgrade ou cluster to a supported version using KubeOne cli.
```suggestion
If your cluster is running an older Kubernetes version, an older KubeOne version has to be used to upgrade your cluster to a supported version first.
```

2023-02-22 13:14 UTC, rastislavs commented on content/kubermatic/main/tutorials-howtos/kubeone-clusters/_index.en.md
> +## Update the Machine Deployment Version
I would add some intro, such as: "Kubelet version on the worker nodes managed by Machine Deployments can be updated as follows:"

2023-02-22 13:14 UTC, rastislavs commented on content/kubermatic/main/tutorials-howtos/kubeone-clusters/_index.en.md
> +
if this needs special attention, I would use `{{% notice info %}}` rather than citation (`>`)

2023-02-22 13:14 UTC, rastislavs commented on content/kubermatic/main/tutorials-howtos/kubeone-clusters/_index.en.md
> +We can then see the details of the cluster.
```suggestion
After the cluster has been imported, we can see the details of the cluster in the dashboard.
```

2023-02-23 09:49 UTC, imharshita commented
@rastislavs ptal

2023-02-23 09:54 UTC, rastislavs commented
/lgtm

2023-02-23 09:55 UTC, rastislavs commented
/approve

2023-02-23 09:56 UTC, merged