Added a tutorial page for VPA in kkp
kubermatic/docs pull request #1750
Opened 2024-09-26 07:05 UTC by dharapvj

Currently, VPA feature in KKP is not well documented. So this PR adds some initial documentation on how to make use of this feature.

2024-09-26 07:06 UTC, dharapvj commented
CC: @toschneck - FYI

2024-09-30 10:16 UTC, xrstf commented on content/kubermatic/main/tutorials-howtos/kkp-autoscaler/vertical-pod-autoscaler/_index.en.md
> +Unlike HPA, VPA does not bundled with kubernetes itself. It must get installed in the cluster separately.
uppercase Kubernetes

2024-09-30 10:17 UTC, xrstf commented on content/kubermatic/main/tutorials-howtos/kkp-autoscaler/vertical-pod-autoscaler/_index.en.md
> +```
This can be tagged as YAML

2024-09-30 10:18 UTC, xrstf commented on content/kubermatic/main/tutorials-howtos/kkp-autoscaler/vertical-pod-autoscaler/_index.en.md
> +```
And please leave an empty line before and after a code block.

2024-09-30 10:18 UTC, xrstf requested changes
Some small nitpickery

2024-10-01 06:28 UTC, dharapvj commented
I have fixed those nits. please recheck

2024-10-07 08:44 UTC, xrstf commented
/approve
/lgtm

2024-10-07 08:51 UTC, merged

2024-10-08 06:45 UTC, ahmedwaleedmalik commented
@dharapvj KKP 2.26 docs were branched out before this PR was merged. We need to copy these docs to [v2.26 directory](https://github.com/kubermatic/docs/tree/main/content/kubermatic/v2.26) as well.