[WIP] KubeLB Documentation improvements 2024-09
kubermatic/docs pull request #1755
Opened 2024-09-28 14:51 UTC by toschneck

- add info about secret name more explicit
- add info about internal IP usage

2024-11-26 10:09 UTC, toschneck commented
Some of the changes have already be addressed, now just smaller adjustments.

2024-11-26 10:18 UTC, toschneck commented
/cc @ahmedwaleedmalik

2024-11-26 10:19 UTC, toschneck commented
/assign @ahmedwaleedmalik

2024-11-26 11:21 UTC, ahmedwaleedmalik requested changes

2024-11-26 11:21 UTC, ahmedwaleedmalik commented on content/kubelb/v1.1/installation/tenant-cluster/_index.en.md
> -helm pull oci://quay.io/kubermatic/helm-charts/kubelb-ccm-ee --version=v1.1.2 --untardir "." --untar
Can you please remove the change for image tag? 

`s/v1.1.1/v1.1.2`

2024-12-03 23:57 UTC, toschneck commented
@ahmedwaleedmalik resolved it, but I think long term it would be good to create a latest tag
![kubelb-ccm-ee · Quay 2024-12-04 00-56-43](https://github.com/user-attachments/assets/d8df10b4-2916-456e-8600-cd880ce0b75b)

2024-12-04 07:26 UTC, ahmedwaleedmalik approved these changes
/approve

2024-12-04 07:26 UTC, merged