take out centos from docs until version 2.24
kubermatic/docs pull request #1804
Opened 2024-11-30 12:21 UTC by julioc-p

2024-12-03 10:33 UTC, julioc-p commented
/hold

2024-12-03 15:33 UTC, julioc-p commented
/cc embik

2024-12-03 15:35 UTC, julioc-p commented
/unhold

2024-12-04 09:07 UTC, embik requested changes

2024-12-04 10:05 UTC, julioc-p commented on content/kubermatic/main/architecture/supported-providers/vsphere/_index.en.md
> +1. Convert it to vmdk: `qemu-img convert -f qcow2 -O vmdk Ubuntu-7-x86_64-GenericCloud.qcow2 Ubuntu-7-x86_64-GenericCloud.vmdk`
Since it was a dummy URL, I did not make much of it. But we can take the 7 out to make it more consistent

2024-12-06 11:01 UTC, embik requested changes

2024-12-06 11:01 UTC, embik commented on content/machine-controller/main/cloud-providers/vsphere/template-vm/qcow2/_index.en.md
> +    image_url="https://cloud.ubuntu.org/ubuntu/7/images/Ubuntu-x86_64-GenericCloud.qcow2"
let's please use a correct URL for Ubuntu images here, even though this is just an example.

2024-12-10 10:49 UTC, embik commented on content/kubermatic/v2.26/architecture/compatibility/os-support-matrix/_index.en.md
> +**Note:** CentOS was removed as a supported OS in KKP 2.26.3
Can we make this a warning please, to highlight it a bit more? You can see examples of that here: https://github.com/kubermatic/docs/blob/main/content/kubermatic/v2.26/installation/install-kkp-ce/_index.en.md?plain=1#L29.

2024-12-10 12:35 UTC, embik approved these changes
/approve

2024-12-10 12:35 UTC, merged