[WIP] Add expose strategy configuration guide
kubermatic/docs pull request #547
Opened 2021-02-17 14:01 UTC by irozzo-1A

2021-02-18 08:32 UTC, irozzo-1A commented
xref: #506

2021-02-22 10:21 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/add_seed_cluster/_index.en.md
> +You can override the global [Expose Strategy]({{< ref "../expose_strategy">}})) at
({{< ref "../expose_strategy">}})) ---> ({{< ref "../expose_strategy">}})

2021-02-22 10:23 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/add_seed_cluster/_index.en.md
> +Depending on the chosen [Expose Strategy]({{< ref "../expose_strategy">}})), the control planes of all user clusters
Same, ({{< ref "../expose_strategy">}}) with one parenthesis.

2021-02-22 10:25 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/add_seed_cluster/_index.en.md
>  for the Seed from the previous step when `kubermatic.example.com` is the main domain where the
Not related to this PR, but it should be reformulated to something like `with kubermatic.example.com being the main domain where the KKP etc.`

2021-02-22 10:25 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/add_seed_cluster_ee/_index.en.md
> +You can override the global [Expose Strategy]({{< ref "../expose_strategy">}})) at
Same -> ({{< ref "../expose_strategy">}})

2021-02-22 10:26 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/add_seed_cluster_ee/_index.en.md
> +Depending on the chosen [Expose Strategy]({{< ref "../expose_strategy">}})), the control planes of all user clusters
Same -> ({{< ref "../expose_strategy">}})

2021-02-22 10:27 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/add_seed_cluster_ee/_index.en.md
>  KKP dashboard/API are available.
Same https://github.com/kubermatic/docs/pull/547/files#r580136413

2021-02-22 10:29 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/expose_strategy/_index.en.md
> +routing the traffic based on one of:
`based on` is enough, no need for `one of`.

2021-02-22 10:29 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/expose_strategy/_index.en.md
> +* destination port: this requires a unique port for each service.
Capital D for destination.

2021-02-22 10:30 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/expose_strategy/_index.en.md
> +Alternatively, the expose strategy can be overridden ad `Seed` level, meaning
`at` not `ad`

2021-02-22 10:38 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/expose_strategy/_index.en.md
> +  components. It binds to the IP advertsed by the Kubernetes API Servier, that
`Server` instead of `Servier`

2021-02-22 10:38 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/expose_strategy/_index.en.md
> +  components. It binds to the IP advertsed by the Kubernetes API Servier, that
`advertised` instead of `advertsed`

2021-02-22 10:39 UTC, youssefazrak commented on content/kubermatic/master/guides/installation/install_kubermatic/_index.en.md
> +  components to the worker nodes (see the [expose strategy]({{< ref "../expose_strategy">}}))
Same, one parenthethis to be removed.

2021-02-22 10:39 UTC, youssefazrak requested changes
Some typos to be fixed, else LGTM.

2021-02-22 13:46 UTC, youssefazrak commented
/lgtm

2021-02-22 13:47 UTC, merged